default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  database: chapter_directory_development

test:
  <<: *default
  database: chapter_directory_test

production:
  <<: *default
  database: chapter_directory_production
