name: Run CI Tasks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Build Database
      run: |
        bin/rails db:setup
        bin/rails db:migrate

    - name: Build Assets
      run: |
        bin/rails css:build
        bin/rails javascript:build

    - name: Run tests
      run: bundle exec rake
