name: Run CI Tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: rails
          MYSQL_DATABASE: chapter_directory_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
        matrix:
          ruby-version: ['3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build Assets
        run: |
          bin/rails css:build
          bin/rails javascript:build

      - name: Run Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:rails@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/chapter_directory_test
        run: |
          bin/rails db:reset
          bin/rails test
